version: "3"
services:
    nginx:
        image: andykuszyk/nginx:[version]
        ports: 
            - "80:80"
            - "443:443"
        networks:
            - net
        volumes:
            - /root/certs-data/:/data/letsencrypt/
            - /etc/letsencrypt/:/etc/letsencrypt/
networks:
    net:
